/**
 * Career Prospect to MDC Program Mapping
 * 
 * This file contains the mapping between career prospects and MDC programs.
 * It's generated by the scraper script and can be manually curated.
 */

export interface ProgramPDFLinks {
  courseList?: string; // URL to "See a complete course list" PDF
  sequenceGuide?: string; // URL to "See a course sequence guide" PDF
}

export interface MDCProgram {
  id: string; // Unique identifier (e.g., "bsn" from URL path)
  name: string; // Full program name
  degreeType: "AA" | "AS" | "BS" | "BA" | "CERT";
  programUrl: string; // URL to the program page on MDC website (e.g., "https://www.mdc.edu/bsn/")
  // This URL is used to fetch PDFs if they weren't found during initial scraping
  careersUrl?: string; // URL to careers subpage if exists
  pdfLinks: ProgramPDFLinks; // Direct PDF links (if found during scraping)
  school?: string; // School name (e.g., "School of Engineering, Technology, and Design")
  concentration?: string; // Concentration name if applicable
  careerProspects: string[]; // List of career prospects/job titles
}

export interface CareerProgramMapping {
  career: string; // Career prospect name (e.g., "Software Developer")
  programs: MDCProgram[]; // Programs that lead to this career
  field?: string; // Field category (e.g., "Technology", "Medicine", "Education")
}

/**
 * Main mapping data structure
 * 
 * This is populated by importing the generated data file.
 */
import { careerToProgramsMapping as generatedMapping } from "./career-program-mapping-data";

export const careerToProgramsMapping: CareerProgramMapping[] = generatedMapping;

/**
 * Get all unique career prospects
 */
export function getAllCareerProspects(): string[] {
  const careers = new Set<string>();
  careerToProgramsMapping.forEach(mapping => {
    careers.add(mapping.career);
    mapping.programs.forEach(program => {
      program.careerProspects.forEach(career => careers.add(career));
    });
  });
  return Array.from(careers).sort();
}

/**
 * Get all unique fields
 */
export function getAllFields(): string[] {
  const fields = new Set<string>();
  careerToProgramsMapping.forEach(mapping => {
    if (mapping.field) {
      fields.add(mapping.field);
    }
  });
  return Array.from(fields).sort();
}

/**
 * Find programs by career prospect
 * Returns programs with their associated field
 */
export function getProgramsByCareer(career: string): Array<MDCProgram & { field?: string }> {
  const normalizedCareer = career.toLowerCase().trim();
  const programs: Array<MDCProgram & { field?: string }> = [];
  const seen = new Set<string>();
  
  careerToProgramsMapping.forEach(mapping => {
    if (mapping.career.toLowerCase() === normalizedCareer) {
      mapping.programs.forEach(program => {
        if (!seen.has(program.id)) {
          programs.push({ ...program, field: mapping.field });
          seen.add(program.id);
        }
      });
    }
    // Also check if any program has this career in its prospects
    mapping.programs.forEach(program => {
      if (program.careerProspects.some(cp => cp.toLowerCase() === normalizedCareer)) {
        if (!seen.has(program.id)) {
          programs.push({ ...program, field: mapping.field });
          seen.add(program.id);
        }
      }
    });
  });
  
  return programs;
}

/**
 * Find programs by field
 */
export function getProgramsByField(field: string): CareerProgramMapping[] {
  const normalizedField = field.toLowerCase().trim();
  return careerToProgramsMapping.filter(
    mapping => mapping.field?.toLowerCase() === normalizedField
  );
}

/**
 * Search programs by career (fuzzy search)
 * Returns programs with their associated field
 */
export function searchProgramsByCareer(searchTerm: string): Array<MDCProgram & { field?: string }> {
  const normalizedSearch = searchTerm.toLowerCase().trim();
  const programs: Array<MDCProgram & { field?: string }> = [];
  const seen = new Set<string>();
  
  careerToProgramsMapping.forEach(mapping => {
    // Check if career name matches
    if (mapping.career.toLowerCase().includes(normalizedSearch)) {
      mapping.programs.forEach(program => {
        if (!seen.has(program.id)) {
          programs.push({ ...program, field: mapping.field });
          seen.add(program.id);
        }
      });
    }
    
    // Check if any program's career prospects match
    mapping.programs.forEach(program => {
      if (program.careerProspects.some(cp => cp.toLowerCase().includes(normalizedSearch))) {
        if (!seen.has(program.id)) {
          programs.push({ ...program, field: mapping.field });
          seen.add(program.id);
        }
      }
    });
    
    // Check if program name matches
    mapping.programs.forEach(program => {
      if (program.name.toLowerCase().includes(normalizedSearch) && !seen.has(program.id)) {
        programs.push({ ...program, field: mapping.field });
        seen.add(program.id);
      }
    });
  });
  
  return programs;
}

/**
 * Get a program by its URL
 * Useful for fetching PDFs when you have the program URL
 */
export function getProgramByUrl(programUrl: string): MDCProgram | null {
  const normalizedUrl = programUrl.toLowerCase().trim();
  
  for (const mapping of careerToProgramsMapping) {
    const program = mapping.programs.find(p => 
      p.programUrl.toLowerCase() === normalizedUrl ||
      p.programUrl.toLowerCase() === `${normalizedUrl}/` ||
      `${p.programUrl.toLowerCase()}/` === normalizedUrl
    );
    if (program) {
      return program;
    }
  }
  
  return null;
}

/**
 * Get a program by its ID
 */
export function getProgramById(programId: string): MDCProgram | null {
  const normalizedId = programId.toLowerCase().trim();
  
  for (const mapping of careerToProgramsMapping) {
    const program = mapping.programs.find(p => p.id.toLowerCase() === normalizedId);
    if (program) {
      return program;
    }
  }
  
  return null;
}

