/**
 * Auto-generated career to program mapping
 * Generated by scrape-mdc-programs.ts
 * Generated on: 2025-11-09T07:12:33.691Z
 * DO NOT EDIT MANUALLY - Regenerate using the scraper script
 */

import type { CareerProgramMapping } from "./career-program-mapping";

export const careerToProgramsMapping: CareerProgramMapping[] = [];
