import type { Scholarship } from "../types";
import { logger } from "./logger";

export interface ProposalFormData {
  studentName: string;
  program: string;
  resumeLink?: string;
  additionalNotes?: string;
}

export async function draftProposal(
  scholarship: Scholarship,
  formData: ProposalFormData
): Promise<string> {
  logger.debug("Starting proposal generation", {
    scholarshipId: scholarship.id,
    studentName: formData.studentName,
    program: formData.program,
  }, "ai");

  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1500));

  const deadline = new Date(scholarship.deadlineISO).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const markdown = `# Scholarship Proposal: ${scholarship.title}

## Executive Summary

${formData.studentName} is applying for the ${scholarship.title} to support their academic journey in ${formData.program}. This proposal outlines their objectives, budget allocation, expected impact, and timeline for achieving their career goals.

**Scholarship Details:**
- Award Amount: $${scholarship.awardUSD.toLocaleString()}
- Deadline: ${deadline}
- Program Focus: ${scholarship.programTags.join(", ")}

## Objectives

### Academic Goals
- Complete coursework in ${formData.program} with a minimum GPA of 3.5
- Obtain relevant certifications aligned with career objectives
- Engage in research projects and collaborative learning opportunities

### Professional Development
- Secure internships in the ${formData.program} field
- Build a portfolio of projects demonstrating technical skills
- Network with industry professionals and attend relevant conferences

### Career Advancement
- Transition into a full-time role in ${formData.program} upon graduation
- Contribute to open-source projects and the tech community
- Pursue advanced certifications and continuous learning

## Budget Allocation

| Category | Amount | Percentage | Purpose |
|----------|--------|------------|---------|
| Tuition & Fees | $${Math.round(scholarship.awardUSD * 0.5).toLocaleString()} | 50% | Direct educational costs |
| Books & Materials | $${Math.round(scholarship.awardUSD * 0.15).toLocaleString()} | 15% | Course materials and resources |
| Technology & Software | $${Math.round(scholarship.awardUSD * 0.15).toLocaleString()} | 15% | Laptop, software licenses, cloud services |
| Professional Development | $${Math.round(scholarship.awardUSD * 0.1).toLocaleString()} | 10% | Conferences, certifications, workshops |
| Living Expenses | $${Math.round(scholarship.awardUSD * 0.1).toLocaleString()} | 10% | Housing and basic needs support |

**Total: $${scholarship.awardUSD.toLocaleString()}**

## Impact Statement

Receiving this scholarship would significantly impact ${formData.studentName}'s ability to:

1. **Focus on Academic Excellence**: Reduce financial stress and allow full concentration on studies
2. **Access Quality Resources**: Invest in necessary technology and learning materials
3. **Pursue Opportunities**: Attend conferences and networking events that would otherwise be unaffordable
4. **Build Professional Portfolio**: Fund projects and certifications that enhance career prospects

${formData.additionalNotes ? `\n### Additional Notes\n\n${formData.additionalNotes}\n` : ""}

## Timeline

### Short-term (0-6 months)
- Complete current semester coursework
- Apply for relevant internships
- Begin certification preparation

### Medium-term (6-12 months)
- Secure and complete internship
- Obtain first professional certification
- Build portfolio with 3-5 significant projects

### Long-term (12-24 months)
- Graduate with honors
- Secure full-time position in ${formData.program}
- Begin contributing to industry through open-source or research

## Supporting Materials

${formData.resumeLink ? `- Resume: [View Resume](${formData.resumeLink})` : "- Resume available upon request"}

## Conclusion

${formData.studentName} is committed to leveraging the ${scholarship.title} to achieve their academic and professional goals in ${formData.program}. This investment will enable them to make meaningful contributions to the ${scholarship.programTags[0]} field while building a foundation for long-term career success.

---

*Generated by SharkScholar Proposal Generator*
*Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}*
`;

  logger.debug("Proposal markdown generated", {
    scholarshipId: scholarship.id,
    markdownLength: markdown.length,
  }, "ai");

  return markdown;
}

